services:
  kachalnaya_pepega:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kachalnaya-pepega
    env_file:
      - .env
    environment:
      - TZ=${TZ}
    volumes:
      - ${MEDIA_DIR}:/media
      - ${BOT_DATA_DIR}:/app/data
      - ${COOKIES_FILE}:/app/cookies.txt
      - ./kachalnaya_pepega:/app/kachalnaya_pepega
    working_dir: /app
    restart: unless-stopped
